services:
    redis:
        container_name: redis
        image: 'redis/redis-stack:latest'
        ports:
            - 6379:6379
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    app:
        container_name: app
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: dev
        command: npm run dev
        ports:
            - 3000:3000
        env_file:
            - ./.env
            - ./.env.docker
        volumes:
            - ./.next:/app/.next
            - ./src:/app/src
            - /app/node_modules
            - /app/.next
        restart: always
        depends_on:
            - redis
